# Generated by Django 4.2.1 on 2023-06-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agritherm_data', '0004_prompt_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
